info:
  contact: {}
paths:
  /v1/admin/login:
    post:
      consumes:
      - multipart/form-data
      description: get admin login
      parameters:
      - description: 用户名
        in: formData
        name: userName
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 管理员登录
      tags:
      - 管理员
  /v1/user/login:
    post:
      consumes:
      - multipart/form-data
      description: get admin login
      parameters:
      - description: 用户名
        in: formData
        name: userName
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 用户登录
      tags:
      - 用户
swagger: "2.0"
